### ISSUE TITLE
linking error

### ISSUE THREAD

**Issue by andyrtr** [OpenPrinting/cups-filters#419]
I'm trying to build from master (84752a7e5f94cd848ad37b28b7e36904dc2daac6) "make install" fails here using Arch Linux:

```
configure:
==============================================================================
Environment settings:
	CFLAGS:                                    -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -std=gnu11 -D_GNU_SOURCE
	CXXFLAGS:                                  -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall  -D_GNU_SOURCE
	LDFLAGS:                                   -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
Build configuration:
	cups-config:     system
	font directory:  /etc/fonts/conf.d
	foomatic:        yes
	init directory:
	cups dom socket: /var/run/cups/cups.sock
	poppler:         yes
	ghostscript:     yes
	gs-path:         system
	mutool:          yes
	mutool-path:     system
	ippfind-path:    system
	imagefilters:    yes
	jpeg:            yes
	pdftocairo-path: system
	pdftops:         hybrid
	pdftops-path:    system
	png:             yes
	php:             no
	php-config:      system
	pstops:          no
	rastertopwg:     no
	shell:           /bin/bash
	test-font:       /usr/share/fonts/TTF/DejaVuSans.ttf
	tiff:            yes
	avahi:           yes
	dbus:            yes
	browsing:        DNSSD,CUPS
	werror:          no
	braille:	 yes
	braille tables:  /usr/share/liblouis/tables
	driverless:      yes
	apple-raster:    rastertopdf
	pclm:            yes
	local queue naming for remote CUPS queues: DNS-SD
	keep generated queues during shutdown:     no
	all ipp printer auto-setup: yes
	only driverless auto-setup: no
	only local auto-setup: no
==============================================================================
...
==> Starting package()...
 /usr/bin/mkdir -p '/build/cups-filters/pkg/cups-filters//usr/lib'
 /bin/sh ./libtool   --mode=install /usr/bin/install -c   libppd.la libcupsfilters.la libfontembed.la '/build/cups-filters/pkg/cups-filters//usr/lib'
libtool: install: /usr/bin/install -c .libs/libppd.so.1.0.0 /build/cups-filters/pkg/cups-filters//usr/lib/libppd.so.1.0.0
libtool: install: (cd /build/cups-filters/pkg/cups-filters//usr/lib && { ln -s -f libppd.so.1.0.0 libppd.so.1 || { rm -f libppd.so.1 && ln -s libppd.so.1.0.0 libppd.so.1; }; })
libtool: install: (cd /build/cups-filters/pkg/cups-filters//usr/lib && { ln -s -f libppd.so.1.0.0 libppd.so || { rm -f libppd.so && ln -s libppd.so.1.0.0 libppd.so; }; })
libtool: install: /usr/bin/install -c .libs/libppd.lai /build/cups-filters/pkg/cups-filters//usr/lib/libppd.la
libtool: warning: relinking 'libcupsfilters.la'
libtool: install: (cd /build/cups-filters/src/cups-filters; /bin/sh "/build/cups-filters/src/cups-filters/libtool"  --silent --tag CXX --mode=relink g++ -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -D_GNU_SOURCE -no-undefined -version-info 1 -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -o libcupsfilters.la -rpath /usr/lib cupsfilters/libcupsfilters_la-attr.lo cupsfilters/libcupsfilters_la-bannertopdf.lo cupsfilters/libcupsfilters_la-bitmap.lo cupsfilters/libcupsfilters_la-check.lo cupsfilters/libcupsfilters_la-cmyk.lo cupsfilters/libcupsfilters_la-colord.lo cupsfilters/libcupsfilters_la-colormanager.lo cupsfilters/libcupsfilters_la-dither.lo cupsfilters/libcupsfilters_la-filter.lo cupsfilters/libcupsfilters_la-ghostscript.lo cupsfilters/libcupsfilters_la-ieee1284.lo cupsfilters/libcupsfilters_la-image.lo cupsfilters/libcupsfilters_la-image-bmp.lo cupsfilters/libcupsfilters_la-image-colorspace.lo cupsfilters/libcupsfilters_la-image-gif.lo cupsfilters/libcupsfilters_la-image-jpeg.lo cupsfilters/libcupsfilters_la-image-photocd.lo cupsfilters/libcupsfilters_la-image-pix.lo cupsfilters/libcupsfilters_la-image-png.lo cupsfilters/libcupsfilters_la-image-pnm.lo cupsfilters/libcupsfilters_la-image-sgi.lo cupsfilters/libcupsfilters_la-image-sgilib.lo cupsfilters/libcupsfilters_la-image-sun.lo cupsfilters/libcupsfilters_la-image-tiff.lo cupsfilters/libcupsfilters_la-image-zoom.lo cupsfilters/libcupsfilters_la-imagetopdf.lo cupsfilters/libcupsfilters_la-imagetops.lo cupsfilters/libcupsfilters_la-imagetoraster.lo cupsfilters/libcupsfilters_la-ipp.lo cupsfilters/libcupsfilters_la-lut.lo cupsfilters/libcupsfilters_la-mupdftoraster.lo cupsfilters/libcupsfilters_la-pack.lo cupsfilters/pclmtoraster.lo cupsfilters/pdf.lo cupsfilters/pdftopdf/pdftopdf.lo cupsfilters/pdftopdf/pdftopdf_jcl.lo cupsfilters/pdftopdf/pdftopdf_processor.lo cupsfilters/pdftopdf/qpdf_pdftopdf_processor.lo cupsfilters/pdftopdf/pptypes.lo cupsfilters/pdftopdf/nup.lo cupsfilters/pdftopdf/intervalset.lo cupsfilters/pdftopdf/qpdf_tools.lo cupsfilters/pdftopdf/qpdf_xobject.lo cupsfilters/pdftopdf/qpdf_pdftopdf.lo cupsfilters/pdftopdf/qpdf_cm.lo cupsfilters/libcupsfilters_la-pdftoippprinter.lo cupsfilters/libcupsfilters_la-pdftops.lo cupsfilters/pdftoraster.lo cupsfilters/libcupsfilters_la-pdfutils.lo cupsfilters/libcupsfilters_la-ppdgenerator.lo cupsfilters/libcupsfilters_la-pstops.lo cupsfilters/libcupsfilters_la-pwgtoraster.lo cupsfilters/libcupsfilters_la-raster.lo cupsfilters/libcupsfilters_la-rastertops.lo cupsfilters/rastertopdf.lo cupsfilters/libcupsfilters_la-rastertopwg.lo cupsfilters/libcupsfilters_la-rgb.lo cupsfilters/libcupsfilters_la-srgb.lo cupsfilters/libcupsfilters_la-texttopdf.lo libppd.la libfontembed.la -lfontconfig -lfreetype -lcups -llcms2 -lqpdf -ltiff -lpng16 -lz -lpoppler-cpp -ldbus-1 -lldap -ltiff -ljpeg -ldl -inst-prefix-dir /build/cups-filters/pkg/cups-filters/)
/usr/bin/ld: cannot find -lfontembed
collect2: error: ld returned 1 exit status
libtool:   error: error: relink 'libcupsfilters.la' with the above command before installing it
make[3]: *** [Makefile:2682: install-libLTLIBRARIES] Error 1
make[2]: *** [Makefile:5875: install-am] Error 2
make[1]: *** [Makefile:5357: install-recursive] Error 1
make: *** [Makefile:5868: install] Error 2
==> ERROR: A failure occurred in package().
```

**Comment by nielsenb-jf** [comment]
I'm seeing this trying to build ef5943a on Fedora as well. I'll report back if I figure out a fix.

**Comment by nielsenb-jf** [comment]
Did a quick bisect, the problem first originates with c7e3f27, not sure why, I feel like I'm missing something obvious.

**Comment by tillkamppeter** [comment]
@pranjanpr the mentioned commit is your `texttopdf()` filter function conversion. Could you have a look what is going wrong here?

**Comment by pranjanpr** [comment]
@tillkamppeter 
This kind of linking issue was coming before I added libfontembed.la in parallel (in Makefile)

**Comment by tillkamppeter** [comment]
@pranjanpr So this should be fixed as I have addressed in a later commit

@nielsenb-jf Please make sure to use the most current state of master.

**Comment by andyrtr** [comment]
It's still failing with current master 7a73e9cf52c7babe9cf515d4522bb1afeed1048a - please have a look.

**Comment by nielsenb-jf** [comment]
I can confirm 7a73e9c fails. Note that this is happening in the `make install` step, the `make` step succeeds.

**Comment by tillkamppeter** [comment]
Unfortunately, I am not able to reproduce this (Ubuntu Impish/21.10). Looks like that you are running inside a package builder.

I also have no idea what to add to `Makefile.am` to prevent this error. I already have defined the dependency of libcupsfilters on libfontembed explicitly there (commit d33583e01).

**Comment by nielsenb-jf** [comment]
Just verified I can reproduce outside of an rpmbuild environment (interesting that a `make clean` is required after an `./autogen.sh`, otherwise the build fails with `make[2]: lm: No such file or directory` when building the driverless-fax unit).

For reference, I'm using the following configure args, taken from the Fedora specfile:

```
./configure --disable-static \
           --disable-silent-rules \
           --with-pdftops=hybrid \
           --enable-dbus \
           --with-rcdir=no \
           --disable-mutool \
           --enable-driverless \
           --enable-pclm \
           --with-apple-raster-filter=rastertopdf \
           --with-remote-cups-local-queue-naming=RemoteName
```

I'm out of time for today, hopefully I can dig into it more next week.

**Comment by andyrtr** [comment]
Bisected this: it got introduced by: c7e3f277e46b52ed6b419f4bb6c1a4716f7d1c5e

**Comment by nielsenb-jf** [comment]
PR #427  fixes both issues I describe in this ticket. The `make[2]: lm: No such file or directory` on first build, and the `/usr/bin/ld: cannot find -lfontembed` during install. I'm not positive it's the "right" fix, the issue appears to be incorrect (or non-existent) dependency resolution during generation of the install portion of the `Makefile`. By reordering things, it ensures libppd and libfontembed are installed before libcupsfilters.

**Comment by tillkamppeter** [comment]
Thanks for the bug report and the PR, as I have merged the PR which fixes the problem for you I close this issue.

**Comment by nielsenb-jf** [comment]
I can confirm I can build from latest master (977fa91).
